name: Test project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 20
      - name: Install bun CLI
        run: npm install -g bun
      - name: Install CI
        run: bun install
      - run: bun test
      - run: bun run build
